apiVersion: v1
kind: Pod

metadata:
  name: nginx-labeled-pod
  namespace: devops-learning

  labels:
    app: nginx
    environment: dev
    tier: frontend

spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
